sudo: required
language: node_js
env:
  global:
  - secure: NJnI+/JwxHYfGOEiVKQfmpJJnm8mZF2oly8Be9Hz1gJLygwX6BGgKMMgx2udJtx9VQF5X3ujxG+C5U3g9S28efR0QN4ygi1pedRgq5h0e7Vctb+UW9ppwRY+BGsRUPfFS53jMegW7Pkxx1VosTKERMQc6zCPbY+nhzCwYmrRs4Tm7aKqVRYCzpel33BGuRbiZiyzHBAPS2J4PMw1JGfg8ty/0xzfS5uk/cTtKXZN6ELXQFaRvMft8O+XM043eSg2rm8gdDxTgTIp5awDNBxqnep2Ew3OdhU3bIoRL9l4gozsJeb7WiL/6nROIdI5q4eK9nldFbAZaE10AeSNvUgxdxZbS9NF5nUC38cCIS+m2eHnS/1AQxisV7BvsEHVdNsHA90+e9ti7sDpLEgeBXNcdQvr7DYBLQUfXKsxhyz7PBZneUUPgopDqU7hWG3dQMd8G5SwWVdAzUfWtTECrPUXNN2HZnIieXykOImJNr9pQz3khjVMqBi81FV8QDGWZF5j1ruuIQAc27S5KM1ieYlCARQ3xSyVXxYSSg47gNE8XVBku4XyfmCVPGg+fcQZ6E1GDdkKpvH+IdlbrW9/h0xPSYtJG82WMUbVMItYHPA1zGMx04jrRadHxa3EfUksj2A27qP9UJspG6tLCzrDpvrwstctThoLSs3K0yc7XBlHDjo=
  - secure: KQj6ht5pRm6iipNe5ZolEHzxUf7dxlFcDp93A3QgieCfyPTLkhiP4jpJ1BRCMZhrHcDvSgnfvhzeR7x6f3mSRv66X58Rl/EslBWAafRYmmSwtBTe3K5IChiX3ehhdrR2M+Fcojvlt0HHuAyIS5a3RkhBoyWsrhKQwmydyqWuR6JFm1vH5O2IbNqse2JV36fhxkzvOQq7HMuvpek+Zz0gG9839NoO6Q64sFRmY7VgloOOOlM2g7wm/lEQq/+6ERPBgQ8KLzfxT3hB9Agn9KPkxiJoK+sgNbRF7mDHmyBj1geiaEJhMPeRwfYlhDs8dqiLyNHJSmAujumORqQ230VtmVOXFUu5X0YvrJ6VkNEcXJ4okmIaTczjur0jlZITCahG1EAMrZ+uitRRtU3Vky6Kd/DdbsXhIl+WtiRgCq1MYcytcEzPo9lVH6Css8wUEMhrJrJ2tlIWAkqNaxMHOQ0K65oUAmFhvggkV/LZy9iVQF7bXlWGokmywDYdKFDp2Go8r+hjFxgAu8MBkQKM5u5lC2OVqRi3oZhdtdcQLNCjNOhORlKAD63lCO9pUvl3/LM8CeOW+8KjU+mf/bD0BQqcg2XDC7Al9KgLBOUBdJGvfRLTM6bEgk2Owm7AOXLxQZ7QOPOr5g/GXy49mykWf6USVSK8pM2bzGq+VqVlMURuji4=
  - secure: hSH4mII/FY7ZEJb2BVO6ornTCoB7obecBnFQzk9Vw5GTYIMCo8/KsqvbN3GOXB6pxV0OBdzxtqHlkOL1jBNM3Kos0AhsOxw0mqW1AdvJJhCJqqYk+t7yQNfA9b1v6VOMVzlkXGN5fPLuOY5rum7/nsfp9NoACoUGoiF4A2kEnhIyHueRYl0nCPYYCPC+c95+KS0WUgxnWzL0Biw5Luk8vcCXZHbMJbUMzzxFipkMu4vzhV6feKxJuSxSFuSE94i99wL6AMkoKzgKRrPwKagdJXX42w5/gdCk6lc7p2j1tuEk3gCUNcEnYH9yYp1DbwBiPE3y6fly779ZdBKkZ57HaqUmCzWZVTDt1zSO+BTre8Ne+m3clKqi6l6BKakAxiQ/ikrhnrhCB7toX5zaLM+xSZ/6ILpI7gFd4DkDXD3TNItqgS7vg9JHbpE49DznjKLg69aMoWpltgIQUTECuJzit9UCrNpP38FuRAH8KS3hdBow4ZJ7soPS0A4o1UHNZHwgQ5YipMqXltpXubECpRTCAL6OaROCZTsyl1+/7dJiscjRBmx451yLVvMD1N4lFAKyGcpH8qNZpasmOq9hAPaWV7QveqEcEaDcChG53qLfJZo8E2t7GV+G1iDWi1Kv+xRVtMjsgEr8zIYyvOHMPFZs8ya3+O7w2aCymXzhABr8i7c=
  - secure: unArSm/rBtUv59zIcbJMVkTVL6QszYqpFLaBcIjWi+77Rr2UkP8V0ElCaall9MD2vZFGMW3YyuvuGX7BtFiJilbuXFoACaJc/R0Lo7BIrIwyNhnryWITBB8wwMkNkkRh+zidpacl/gACvv/xcpH0Ea716+XjD7BjKtzfqeh/fUPpQ6npK7rbTVQ65nKSr+ews+Tk6ReKnIjslHaipO2xuCyETdV/q/F+GG0zUS25pI3tagdnZfEOnsI9gS3FueU3pZ1FdwhfrpbwpfujJbQ11lyCpIybJrE4nglRczDmijSoHD5QWW5wQy2CVCCZv4lbR4iMwXzGMs9nNyNwkDX33kgs0OvIhyXrvMOFk7ThHC4+flTdyf/1KNRhSyylUtoeSRi8e25ClaCscm4XjTMKjeKOpS7t04g3wDvyJ6nDplM9Cla42IB7VWZXquZ146Gb1XJQlHneZxCJaM8hlhyjwvQlMLkHIbgTuZUnQD1XY+KMIMP+iqenyHRTHfFRm/b7Kb85RyxNvStlae6nm+lP0BGWiGyfPvgc4wv9DHOmt+J2X7J95dZTaSAsd3rgFtk5ogz3lZrVlPUALyMNSaezOZNGOx+P02tSsA2Ss+HVhWEGNBUVvTOXI0kjii3TyF8iXOJ+G/BeOHssw7gLI/fiEXQaNB9HGv99j9b9x1YKPCo=
  - COMMIT=${TRAVIS_COMMIT::8}
services:
- docker
before_install:
- docker build -t web-login-site/web-login-site .
- docker run -dt -p 127.0.0.1:443:443 web-login-site/web-login-site
- docker ps -a
- docker run web-login-site/web-login-site /bin/sh -c "npm test"
script:
- echo "Tests succeed!"

after_success:
- docker login -u $TENABLE_IO_CONTAINER_SECURITY_EMAIL -p $TENABLE_IO_CONTAINER_SECURITY_PASSWORD
  registry.cloud.tenable.com
- export REPO=web-login-site/web-login-site
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT registry.cloud.tenable.com/$REPO:$TAG
- docker tag $REPO:$COMMIT registry.cloud.tenable.com/$REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push registry.cloud.tenable.com/$REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push registry.cloud.tenable.com/$REPO:$TAG
- ls
- ./tiocs-check.sh
